"""Add estimated delivery fields to Orders

Revision ID: 10509bf9d9a6
Revises: 3708866bee52
Create Date: 2025-08-22 15:47:29.716809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10509bf9d9a6'
down_revision = '3708866bee52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimated_delivery_at', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('estimated_delivery_note', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('estimated_delivery_note')
        batch_op.drop_column('estimated_delivery_at')

    # ### end Alembic commands ###
