"""Add sort_order to products

Revision ID: 19269d35ed5e
Revises: 4e7573159571
Create Date: 2025-11-16 17:24:32.335910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19269d35ed5e'
down_revision = '4e7573159571'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=True))

    with op.batch_alter_table('subcategories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subcategories', schema=None) as batch_op:
        batch_op.drop_column('sort_order')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('sort_order')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('sort_order')

    # ### end Alembic commands ###
