"""add discount_code and discount_value to Orders

Revision ID: 1b748a2e4f8c
Revises: 10509bf9d9a6
Create Date: 2025-11-08 09:23:21.059498

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1b748a2e4f8c'
down_revision = '10509bf9d9a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_logs')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('discount_value', sa.Float(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('discount_value')
        batch_op.drop_column('discount_code')

    op.create_table('email_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('email_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='email_logs_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='email_logs_pkey')
    )
    # ### end Alembic commands ###
