"""Update DeliveryEstimateConfig to single delivery_days and range_days

Revision ID: 2e0353f8b8c9
Revises: 3cd34e623524
Create Date: 2025-08-02 10:28:21.283948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e0353f8b8c9'
down_revision = '3cd34e623524'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_estimate_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_days', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('range_days', sa.Integer(), nullable=False))
        batch_op.drop_column('start_date')
        batch_op.drop_column('end_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_estimate_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.drop_column('range_days')
        batch_op.drop_column('delivery_days')

    # ### end Alembic commands ###
