"""empty message

Revision ID: 4e7573159571
Revises: b080f1db03c8
Create Date: 2025-11-16 05:42:32.485038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e7573159571'
down_revision = 'b080f1db03c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titulo_seo', sa.String(length=180), nullable=True))
        batch_op.add_column(sa.Column('h1_seo', sa.String(length=180), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('h1_seo')
        batch_op.drop_column('titulo_seo')

    # ### end Alembic commands ###
