"""añadir campos de envío

Revision ID: af200f1273a4
Revises: 6859bb933e8b
Create Date: 2025-07-09 08:17:31.923486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af200f1273a4'
down_revision = '6859bb933e8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_type', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('shipping_cost', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_details', schema=None) as batch_op:
        batch_op.drop_column('shipping_cost')
        batch_op.drop_column('shipping_type')

    # ### end Alembic commands ###
