"""empty message

Revision ID: b080f1db03c8
Revises: 1b748a2e4f8c
Create Date: 2025-11-14 21:19:17.618777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b080f1db03c8'
down_revision = '1b748a2e4f8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion_seo', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('es_mas_vendido', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('es_nuevo_diseno', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('es_nuevo_diseno')
        batch_op.drop_column('es_mas_vendido')
        batch_op.drop_column('descripcion_seo')

    # ### end Alembic commands ###
