"""Add added_at nullable True to Cart

Revision ID: cedbce61fddd
Revises: 2e0353f8b8c9
Create Date: 2025-08-05 23:07:51.974739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cedbce61fddd'
down_revision = '2e0353f8b8c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('added_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_column('added_at')

    # ### end Alembic commands ###
