"""empty message

Revision ID: 94f55459ff47
Revises: 51dc1ba448ce
Create Date: 2024-10-23 07:17:01.577151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94f55459ff47'
down_revision = '51dc1ba448ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('posts_slug_key', type_='unique')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('posts_slug_key', ['slug'])

    # ### end Alembic commands ###
